name: Ohto Workflow

on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.TOKEN }}
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
           
       - name: Building
         continue-on-error: true
         run: |
           sudo apt -qq update && sudo apt -qq install -y --no-install-recommends ffmpeg neofetch
           git clone ${{ secrets.REPO_URL }} ohto && cd ohto && pip3 install -r requirements.txt
           pwd
       - name: Ohto Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           pwd
           cd ohto
           wget -O .env ${{ secrets.ENV }}
           echo environment loaded!
           python3 main.py